var text ="I Love programing"

console.log(text[0])
console.log(text.charAt(0))
console.log(text.charCodeAt(0))
console.log(text + " & react")
console.log(text.concat(" & react"))
console.log(text.trim())
console.log(text.toLowerCase())
console.log(text.toUpperCase())
console.log(text.search("Love"))
console.log(text.indexOf("Love"))
console.log(text.includes("Love"))
console.log(text.slice(2 , 6))
console.log(text.substr(2 , 5))
console.log(text.substring(2 , 6))
console.log(Math.PI)
console.log(Math.pow(2 , 4))
console.log(Math.sqrt(25))
console.log(Math.abs(-5))
console.log(Math.min(1, 20, 60, 88, 100))
//console.log(Math.Mix(1, 20, 60, 88, 100))
console.log(Math.floor(20.1))
console.log(Math.floor(20.9))
console.log(Math.trunc(20.1))
console.log(Math.trunc(20.9))
console.log(Math.round(12.6))
console.log(Math.ceil(12.1))
console.log(Math.random() * 10)